### ISSUE TITLE
Avoid partial argument match warning

### ISSUE THREAD

**Issue by joshuaulrich** [randy3k/rchitect#12]
Hi, thanks for rchitect and radian! The patch below avoids partial argument matching of `env` to `envir`.

```diff
$ git diff rchitect/completion.py
diff --git a/rchitect/completion.py b/rchitect/completion.py
index 4ab0aba..6981985 100644
--- a/rchitect/completion.py
+++ b/rchitect/completion.py
@@ -20,7 +20,7 @@ tryCatch(
     }},
     error = function(e) {{
         if ({settimelimit}) base::setTimeLimit()
-        assign("comps", NULL, env = utils:::.CompletionEnv)
+        assign("comps", NULL, envir = utils:::.CompletionEnv)
     }}
 )
 """
```

You can trigger the warning by setting this in your `.Rprofile`:

```r
options(warnPartialMatchArgs = TRUE,
        warnPartialMatchAttr = TRUE,
        warnPartialMatchDollar = TRUE)
```

And then call `head(mtcars)` as soon as you start radian. This doesn't cause any problem for me. I wanted to point it out because it's best practice to use the full names of all arguments when programming in order to avoid any partial matches.

**Comment by randy3k** [comment]
Thanks. You are absolutely correct.

**Comment by randy3k** [comment]
Do you want to submit a PR?
