### ISSUE TITLE
Trouble installing on M1

### ISSUE THREAD

**Issue by pat-s** [randy3k/rchitect#15]
Trying to install `rchitect` (actually `radian`) on a native py3 interpreter.

py3 was installed via `brew install python3`. Other packages can be installed just fine via their arm eggs. Do you know what might be wrong here?

Rosetta2 is not installed on the system.

```py
which python3         
/opt/homebrew/bin/python3

pip3 install radian

Collecting radian
  Using cached radian-0.5.9.tar.gz (47 kB)
Collecting rchitect<0.4.0,>=0.3.29
  Using cached rchitect-0.3.29.tar.gz (29 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/homebrew/opt/python@3.9/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/s9/94x83w5x5gv1tkw6pgcvy55r0000gn/T/pip-install-shcma3zf/rchitect_c333ac5caf63419a9cfa70d48c468b2b/setup.py'"'"'; __file__='"'"'/private/var/folders/s9/94x83w5x5gv1tkw6pgcvy55r0000gn/T/pip-install-shcma3zf/rchitect_c333ac5caf63419a9cfa70d48c468b2b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/s9/94x83w5x5gv1tkw6pgcvy55r0000gn/T/pip-pip-egg-info-wtf0bbq8
         cwd: /private/var/folders/s9/94x83w5x5gv1tkw6pgcvy55r0000gn/T/pip-install-shcma3zf/rchitect_c333ac5caf63419a9cfa70d48c468b2b/
    Complete output (29 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/s9/94x83w5x5gv1tkw6pgcvy55r0000gn/T/pip-install-shcma3zf/rchitect_c333ac5caf63419a9cfa70d48c468b2b/setup.py", line 32, in <module>
        setup(
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/dist.py", line 455, in __init__
        _Distribution.__init__(self, {
      File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/dist.py", line 801, in finalize_options
        ep(self)
      File "/opt/homebrew/lib/python3.9/site-packages/setuptools/dist.py", line 808, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/private/var/folders/s9/94x83w5x5gv1tkw6pgcvy55r0000gn/T/pip-install-shcma3zf/rchitect_c333ac5caf63419a9cfa70d48c468b2b/.eggs/cffi-1.14.5-py3.9-macosx-11-arm64.egg/cffi/setuptools_ext.py", line 219, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/private/var/folders/s9/94x83w5x5gv1tkw6pgcvy55r0000gn/T/pip-install-shcma3zf/rchitect_c333ac5caf63419a9cfa70d48c468b2b/.eggs/cffi-1.14.5-py3.9-macosx-11-arm64.egg/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/private/var/folders/s9/94x83w5x5gv1tkw6pgcvy55r0000gn/T/pip-install-shcma3zf/rchitect_c333ac5caf63419a9cfa70d48c468b2b/.eggs/cffi-1.14.5-py3.9-macosx-11-arm64.egg/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "rchitect/src/build.py", line 5, in <module>
        ffibuilder = FFI()
      File "/private/var/folders/s9/94x83w5x5gv1tkw6pgcvy55r0000gn/T/pip-install-shcma3zf/rchitect_c333ac5caf63419a9cfa70d48c468b2b/.eggs/cffi-1.14.5-py3.9-macosx-11-arm64.egg/cffi/api.py", line 48, in __init__
        import _cffi_backend as backend
    ImportError: dlopen(/private/var/folders/s9/94x83w5x5gv1tkw6pgcvy55r0000gn/T/pip-install-shcma3zf/rchitect_c333ac5caf63419a9cfa70d48c468b2b/.eggs/cffi-1.14.5-py3.9-macosx-11-arm64.egg/_cffi_backend.cpython-39-darwin.so, 2): no suitable image found.  Did find:
        /private/var/folders/s9/94x83w5x5gv1tkw6pgcvy55r0000gn/T/pip-install-shcma3zf/rchitect_c333ac5caf63419a9cfa70d48c468b2b/.eggs/cffi-1.14.5-py3.9-macosx-11-arm64.egg/_cffi_backend.cpython-39-darwin.so: mach-o, but wrong architecture
        /private/var/folders/s9/94x83w5x5gv1tkw6pgcvy55r0000gn/T/pip-install-shcma3zf/rchitect_c333ac5caf63419a9cfa70d48c468b2b/.eggs/cffi-1.14.5-py3.9-macosx-11-arm64.egg/_cffi_backend.cpython-39-darwin.so: mach-o, but wrong architecture
```

**Comment by randy3k** [comment]
It looks like an issue of the python package cffi. Maybe trying to reinstall it?

**Comment by pat-s** [comment]
Thanks.

Meanwhile I suspect that something is wrong with the python installing itself, all other packages error during load-time as well with the "wrong arch" message.

This is weird as all of this is run on a M1 without Rosetta and in an `arm64` terminal. R is working fine (arm). Python installed via brew.

So yes, there might be no relation to `rchitect` at all, I might have just by accident come across this particular issue then with `cffi`. Need to double-check on other M1 machines and get a better idea of what might be wrong.

**Comment by pat-s** [comment]
After doing some research and asking Q's, I've come across that there are no [arm64 wheels for macOS on Pypi for rchitect](https://pypi.org/project/rchitect/#files). The same applies for `radian`.

I'll try to build both natively on the machine for now.

Are there any plans to add such wheels in the near future?

**Comment by randy3k** [comment]
But how did you manage to install a wheel which is not compatible with your python distribution. 

By the way, radian is a pure python package, so you don't need to compile anything.

**Comment by pat-s** [comment]
I was not able to install it. It downloads the wheel for x86_64 and complains during installation. 

AFAICS I would need to build the wheel myself on the machine and then install it?

**Comment by randy3k** [comment]
I just wonder why it downloaded the intel wheel for the first place.

**Comment by pat-s** [comment]
Looks like that's the default behaviour of pip? But that's just a guess of mine 😄 

Would you expect pip to refuse to download anything if it does not find a wheel for the given arch?

**Comment by randy3k** [comment]
Ya, it's what I expect. Though I don't have any idea how it was done internally.

**Comment by randy3k** [comment]
Found a post about cffi: https://groups.google.com/g/python-cffi/c/LtPdUxAT-M0/m/h0XTw3c9AAAJ
The author of the python package cffi said
>  I have no clue why pip picks the x86_64 wheel instead of building from
source, and I don't want to know, at this point.

**Comment by randy3k** [comment]
Install everything (in particular cffi) from source should fix the issue.
```
pip install --no-binary :all: radian
```

**Comment by pat-s** [comment]
Thanks for deep diving!

FWIW we've completely started fresh on a new machine and 

```
brew install python3
pip3 install radian
```

just worked OOB and `radian` can just be loaded normally now - now idea why 🤷 😆 

I was prepared to build from source but apparently now everything works. Weird.

**Comment by randy3k** [comment]
I believe that you have already built from source as both radian and cffi does not have arm wheels 😄

**Comment by pat-s** [comment]
Indeed, probably. 

No idea what might have been wrong on the first machine. So strange.

Used the same script to bootstrap the install from scratch. 😄
