### ISSUE TITLE
Can install rchitect with pip but not with mamba

### ISSUE THREAD

**Issue by lmgibson** [randy3k/rchitect#17]
I am debugging an error where I am unable to install radian with mamba but can with pip. The root issue seems to be due to mamba unable to find rchitect. 

When running `mamba install radian` this is the error I get.
```
Encountered problems while solving:
  - nothing provides rchitect >=0.3.30,<0.4.0 needed by radian-0.5.10-pyhd8ed1ab_0
```

I then tried to install rchitect directly with `mamba install rchitect` but I receive this error:
```
Looking for: ['rchitect']

pkgs/main/osx-arm64      [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
conda-forge/osx-arm64    [====================] (00m:00s) No change
pkgs/r/osx-arm64         [====================] (00m:00s) 404 Failed
pkgs/r/noarch            [====================] (00m:00s) No change
conda-forge/noarch       [====================] (00m:00s) No change

Pinned packages:
  - python 3.9.2

Encountered problems while solving:
  - nothing provides requested rchitect
```

I then tried installing rchitect using pip in a venv:
```
Collecting rchitect
  Using cached rchitect-0.3.32-cp39-cp39-macosx_11_0_arm64.whl (77 kB)
Collecting six>=1.9.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Processing /Users/metaverse/Library/Caches/pip/wheels/9d/fd/b3/1c45c7d2a111aa5a29f24e12609ea5bc8a010d1b8351488796/cffi-1.14.5-cp39-cp39-macosx_11_0_arm64.whl
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Installing collected packages: six, pycparser, cffi, rchitect
Successfully installed cffi-1.14.5 pycparser-2.20 rchitect-0.3.32 six-1.16.0
```

Which allowed me to successfully install radian via pip. 

Note, I did also try install via conda rather than mamba and recieved the following error (`conda install -c conda-forge rchitect`):

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - rchitect

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch
```

This isn't a huge issue because I was able to install via pip, but I'm wondering what is preventing me from installing through conda? Some version information:

```
mamba 0.14.0
conda 4.10.1
pip 21.1.2
python 3.9.2
```

Let me know if you need more information. Thank you!

**Comment by psobolewskiPhD** [comment]
In case anyone is still interested:
using conda-forge, `rchitect` can be installed on arm64 macOS with no issue using conda/mamba. 
FYI: `anaconda` still does not support arm64 (Apple Silicon M1), so for conda you need:
https://github.com/conda-forge/miniforge
and then you can always install mamba if you want.
(Also for the record, `radian` also installs fine on arm64 with conda/mamba using conda-forge and picks up on a native arm64 CRAN R install.)
I think this issue can be closed.
