### ISSUE TITLE
LD_LIBRARY_PATH issue

### ISSUE THREAD

**Issue by t-kalinowski** [randy3k/rchitect#3]
![screenshot from 2018-09-12 13-44-37](https://user-images.githubusercontent.com/8462255/45443227-18a8db80-b692-11e8-90e8-4b247b51269a.png)

**Comment by randy3k** [comment]
It is a well-known issue of R. Unfortunately, it is out of the scope of `rapi`. It will be the job of the user/package which calls rapi.

For instance, it is how `rtichoke` handles it
https://github.com/randy3k/rtichoke/blob/master/rtichoke/__init__.py#L54

**Comment by t-kalinowski** [comment]
Thank you for responding. 
Sorry if this is a naive question, but shouldn't that code you linked to live in this package? Being able to load and start R seems fundamental to the purpose of `rapi`.

**Comment by randy3k** [comment]
It really depends on how the `rapi` is called; interactively or not!? You probably not want to replace your current process by a new one in an interactive environment.

Some remark on README will be helpful though.

**Comment by t-kalinowski** [comment]
Thanks for adding the section to the README.
