### ISSUE TITLE
can't run example in README (rcall throws error)

### ISSUE THREAD

**Issue by t-kalinowski** [randy3k/rchitect#4]
Attached is a screenshot of the first one, but I get a similar one for other examples further down the readme too that use `rcall`. Do you have any suggestions for how to debug this?
![screenshot from 2018-09-17 16-15-01](https://user-images.githubusercontent.com/8462255/45647903-13360180-ba95-11e8-90d8-902177cfebc4.png)

**Comment by randy3k** [comment]
Are you using this version of reticulate? https://github.com/rstudio/reticulate/pull/279

**Comment by t-kalinowski** [comment]
I just tried it, same error
![screenshot from 2018-09-17 16-48-01](https://user-images.githubusercontent.com/8462255/45649548-9f4a2800-ba99-11e8-8f97-e2de9830fe1a.png)

**Comment by randy3k** [comment]
It’s working fine on my Mac. R3.5.1 and python 3 by the way.

**Comment by t-kalinowski** [comment]
I was doing it in python 2. I just tried it in python 3 and it works there (also the CRAN version of reticulate). 

is there anyway we can get that working in python 2?

**Comment by randy3k** [comment]
Let me check what's the issue on python 2.

**Comment by randy3k** [comment]
I could reproduce your error on python 2.

**Comment by randy3k** [comment]
You will need 
```py
from __future__ import unicode_literals
```

Update: it is not needed if you use the master branch of rapi.

**Comment by t-kalinowski** [comment]
Thank you!
