### ISSUE TITLE
Please do not install tests

### ISSUE THREAD

**Issue by yurivict** [randy3k/rchitect#5]
```%%PYTHON_SITELIBDIR%%/tests/test_callback.py``` conflicts with other packages that also erroneously install tests like this.

**Comment by randy3k** [comment]
I have no idea why you have the tests installed. They are in principle excluded.

**Comment by yurivict** [comment]
They are being installed by dustutils during the standard installation process. I had to remove the ```tests``` directory to fix this.

**Comment by randy3k** [comment]
What versions of python and setuptools do you have?

**Comment by yurivict** [comment]
python-2.7, python-3.6 and setuptools-40.6.2

**Comment by randy3k** [comment]
71bd3624ffc2b78a51f729c78061c905543137cb should fix it.
