### ISSUE TITLE
juptyer notebook

### ISSUE THREAD

**Issue by randy3k** [randy3k/rchitect#9]
It was reported by https://github.com/randy3k/radian/issues/96 that rchitect is *not* working in juypter notebook. More investigations are needed.

**Comment by gfleetwood** [comment]
As soon as I try to run this code the kernel crashes:

```
from rchitect import *
a = reval("1:5")
```

**Comment by randy3k** [comment]
There is a bug when running rchitect non interactively. A workaround, for now, is to run first
```
rchitect.init(["rchitect", "--quiet", "--vanilla"])
```

**Comment by gfleetwood** [comment]
Great! Thanks for all the help across the two issues.

**Comment by randy3k** [comment]
It is fixed with the current master.

**Comment by randy3k** [comment]
v0.3.4 is out.
